nginx:
  name: nginx
  labels:
    id: "c0922317"
    app: nginx
    env: dev
    stack: wordpress
  image:
    repository: sebasnates/nginx_ica
    tag: latest
    pullPolicy: Always
  replicas: 1
  containerPorts:
      nginx: 80
