apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  labels:
{{- toYaml .Values.nginx.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      id: {{ .Values.nginx.labels.id }}
  replicas: {{ .Values.nginx.replicas }}
  template:
    metadata:
      labels:
{{- toYaml .Values.nginx.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.nginx.name }}
        image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Values.nginx.name }}-configmap
              optional: false
          - secretRef:
              name: {{ .Values.nginx.name }}-secret
              optional: false
        ports:
        - containerPort: {{ .Values.nginx.containerPorts.nginx }}
      #   volumeMounts:
      #   - name: {{ .Values.nginx.name }}-volume
      #     mountPath: /var/lib/mysql       # Path inside container
      # volumes:
      # - name: {{ .Values.nginx.name }}-volume
      #   hostPath:
      #     path: /var/lib/wp-data     # Path in host machine
