apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  labels:
{{- toYaml .Values.nginx.labels | nindent 4 }}
spec:
  ports:
  - port: 8090            # the port on which the service is listening
    protocol: TCP
    targetPort: {{ .Values.nginx.containerPorts.nginx }}      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  type: NodePort
  selector:
    id: {{ .Values.nginx.labels.id }}    # Pod label that service is using to select Pods
